project:
  type: website
  output-dir: _site #this is default
  preview: 
    port: 3218
    browser: false

website:
  title: "math17300"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: lectures.qmd
        text: Lectures
      - href: homework.qmd
        text: Homework Answers
      - href: project.qmd
        text: Project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
execute: 
  freeze: auto
  echo: false
