project:
  type: website
  output-dir: _site #this is default
  preview: 
    port: 3218

website:
  title: "math17300"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
execute: 
  freeze: auto



