---
title: "Homework Chapter 6"
format: html
---

```{r}
#| include: false
g <- glue::glue
library(ggplot2)
sapply(list.files(here::here('R'), full.names = T), source)
```

## Section 1

### Q18

```{r}
curve(dunif(x, min = 25, max = 50), from = 20, to = 55, col = "blue", lwd = 3, ylab = "f(x)", xaxt = 'n')
axis(side = 1, at = seq(20, 55, by = 5))
```

$$
f(x) = \frac{1}{b-a} = \frac{1}{50 - 25} = \frac{1}{25}
$$

$$
P(x > 45) = (50 - 45) * \frac{1}{25} = 5/25 = .2
$$

$$
P(35 < x < 45) = (45 - 35) * \frac{1}{25} = 10/25 = .4
$$

$$
P(x < 40) = (40 - 25) * \frac{1}{25} = 15/25 = .6
$$

### Q19


```{r}
curve(dexp(x, rate = 1/365), from = 0, to = 365*2, col = "blue", lwd = 3, ylab = "f(x)", xaxt = 'n')
axis(side = 1, at = c(0, 180, 365, 356*2))
```

$$
P(x < 180) = 1 - e^{-\frac{1}{365} \times 180} = .39
$$

$$
P(x > 365) = e^{-365/365} = .37
$$


- P(A) = battery 1 lasts
- P(B) = battery 2 lasts

Assume A and B are independent

$$
P(A \cap B) = P(A)P(B) = .37 * .37 = 0.14
$$

## Section 2

### Q46-48

46

```{r}
pnorm(13, 12.9, 1.6) - pnorm(12, 12.9, 1.6)
```


47
```{r}
1 - pnorm(16, 14.1, 1.6)
```

48


The chance of seeing that in a boy is:
```{r}
pnorm(10, 14.1, 1.6)
```

Less than 1% chance of observing a baby boy that was less than 10 pounds.

### Q68

```{r}
mu <- 185
sd <- 20
```

a. `r pnorm(195, mu, sd, lower = FALSE)`

b. `r pnorm(215, mu, sd) - pnorm(195, mu, sd)`

c. Probabilty of more than 215 for 1: `r (xx <- 1 - pnorm(215, mu, sd))` 

2 people independently `r xx^2`