---
title: "Homework Chapter 8"
format: html
---


## Section 2

### Q30

$$
7.2 \pm 1.96*\frac{5.6}{\sqrt{200}}
$$

### Q32

a. The population is the cost of rooms from the three hotel chains.

b. $150 \pm 1.96\frac{17.2}{sqrt{50}}$

c. $165 \pm 1.96\frac{22.5}{sqrt{50}}$
d. $125 \pm 1.96\frac{12.8}{sqrt{50}}$
e. (see figure 8.5)

## Section 3

### Q18

```{r}
2*1.96 * 10/sqrt(100)
```

### Q19

```{r}
2*1.96 * 10/sqrt(200)
```


### Q20

```{r}
2*1.96 * 10/sqrt(400)
```

### Q31

a. `r 54 + c(-1.96, 1.96) * 12.7/sqrt(1136)`
b. `r 72 + c(-1.96, 1.96) * 10.4/sqrt(795)`

### Q37

a. `r .58 + c(-1.96, 1.96) * sqrt(.58*(1-.58)/100)`
b. It supports the claim because 67% is within the boundary of interval

## Section 4

```{r}
z_conf_int <- function(x1, sd1, n1, x2,  sd2,n2, alpha = .05) {

    se <- sqrt(sd1^2/n1 + sd2^2/n2)
    message("Point: ", round(x1 - x2, 2))
    message("SE: ", round(se, 2))
    message("Margin: ", round(-se*qnorm(alpha/2), 2))
    
    x <- round((x1 - x2) + c(1, -1)*qnorm(alpha/2)*se, 2)
    message("CI: [", x[1], ", ", x[2], "]")
}
```

### Q14


```{r}
z_conf_int(21.3, 2.6, 30, 13.4, 1.9, 30)
```
### Q19

```{r}
z_conf_int(1122, 194, 100, 1048, 165, 100)
```

## Section 5


### Q13


```{r}
p1 <- 12/56
p2 <- 8/32


z_conf_int(p1, sqrt(p1*(1-p1)), 56, p2, sqrt(p2*(1 - p2)), 32)

```

### Q23



a. 
```{r}
p1 <- 23/(41)
p2 <- 10/(32)
```

Point estimate:
```{r}
p1 |> signif(2)
```

Margin:
```{r}
signif(sqrt(p1 * (1-p1)/(41)) * 1.96, 2)
```
b.

```{r}
z_conf_int(p1, sqrt(p1*(1-p1)), 41 , p2, sqrt(p2*(1 - p2)),  32)

```


## Section 7
